/* RKN_GLOBAL_BUSINESS_ENGINE_V1 */

import type { RknBusinessEventDefinition } from "./contracts";

export const RKN_BUSINESS_EVENT_CATALOG: readonly RknBusinessEventDefinition[] = [
  {
    key: "USER_APPROVED",
    domain: "EMAIL_NOTIFICATION",
    severity: "INFO",
    emailEligible: true,
    description: "User access approved.",
  },
  {
    key: "TEMP_PASSWORD_CREATED",
    domain: "EMAIL_NOTIFICATION",
    severity: "INFO",
    emailEligible: true,
    description: "Temporary password created.",
  },
  {
    key: "ORDER_OBSERVED",
    domain: "ORDER",
    severity: "INFO",
    emailEligible: false,
    description: "Order observation accepted into the canonical pipeline.",
  },
  {
    key: "ORDER_READY",
    domain: "ORDER",
    severity: "INFO",
    emailEligible: false,
    description: "Order is validated and ready for controlled business effects.",
  },
  {
    key: "ORDER_REVIEW_REQUIRED",
    domain: "ORDER",
    severity: "REVIEW",
    emailEligible: true,
    description: "Order requires human review before mutation.",
  },
  {
    key: "ORDER_CANCELLED",
    domain: "ORDER",
    severity: "INFO",
    emailEligible: false,
    description: "Order cancellation observed.",
  },
  {
    key: "INVENTORY_LOW",
    domain: "INVENTORY",
    severity: "WARNING",
    emailEligible: true,
    description: "Inventory crossed a configured low-stock threshold.",
  },
  {
    key: "INVENTORY_ADJUSTED",
    domain: "INVENTORY",
    severity: "INFO",
    emailEligible: false,
    description: "Inventory adjustment recorded through the ledger boundary.",
  },
  {
    key: "INVENTORY_RECONCILIATION_FAILED",
    domain: "REVIEW_RECON",
    severity: "CRITICAL",
    emailEligible: true,
    description: "Inventory balance and ledger could not be reconciled.",
  },
  {
    key: "HPP_UPDATED",
    domain: "COSTING_HPP",
    severity: "INFO",
    emailEligible: false,
    description: "Effective HPP was updated.",
  },
  {
    key: "HPP_MISSING",
    domain: "COSTING_HPP",
    severity: "REVIEW",
    emailEligible: true,
    description: "A transaction requires HPP but no valid historical HPP exists.",
  },
  {
    key: "BORROW_CREATED",
    domain: "BORROW_TRANSFER",
    severity: "INFO",
    emailEligible: true,
    description: "Borrow or transfer obligation created.",
  },
  {
    key: "BORROW_DUE",
    domain: "BORROW_TRANSFER",
    severity: "WARNING",
    emailEligible: true,
    description: "Borrow obligation reached its due condition.",
  },
  {
    key: "BORROW_SETTLED",
    domain: "BORROW_TRANSFER",
    severity: "INFO",
    emailEligible: true,
    description: "Borrow obligation settled.",
  },
  {
    key: "PAYROLL_READY",
    domain: "PAYROLL",
    severity: "INFO",
    emailEligible: true,
    description: "Payroll calculation is ready for controlled review.",
  },
  {
    key: "PAYROLL_APPROVAL_REQUIRED",
    domain: "PAYROLL",
    severity: "REVIEW",
    emailEligible: true,
    description: "Payroll requires approval before posting.",
  },
  {
    key: "PAYROLL_POSTED",
    domain: "PAYROLL",
    severity: "INFO",
    emailEligible: true,
    description: "Payroll posting completed.",
  },
  {
    key: "SETTLEMENT_READY",
    domain: "FINANCE_SETTLEMENT",
    severity: "INFO",
    emailEligible: false,
    description: "Marketplace or internal settlement is ready.",
  },
  {
    key: "SETTLEMENT_MISMATCH",
    domain: "FINANCE_SETTLEMENT",
    severity: "WARNING",
    emailEligible: true,
    description: "Settlement does not reconcile with expected ledger values.",
  },
  {
    key: "AUTOMATION_REVIEW_REQUIRED",
    domain: "AUTOMATION",
    severity: "REVIEW",
    emailEligible: true,
    description: "Automation stopped at a human review boundary.",
  },
  {
    key: "AUTOMATION_FAILED",
    domain: "AUTOMATION",
    severity: "CRITICAL",
    emailEligible: true,
    description: "Automation exhausted its safe execution path.",
  },
  {
    key: "CONNECTOR_DEGRADED",
    domain: "MARKETPLACE",
    severity: "WARNING",
    emailEligible: true,
    description: "A connector entered a degraded state.",
  },
  {
    key: "MARKETPLACE_EVENT_RECEIVED",
    domain: "MARKETPLACE",
    severity: "INFO",
    emailEligible: false,
    description: "A provider event was received for normalization.",
  },
  {
    key: "SHOPEE_SYNC_FAILED",
    domain: "MARKETPLACE",
    severity: "WARNING",
    emailEligible: true,
    description: "Shopee synchronization failed.",
  },
  {
    key: "TIKTOK_SYNC_FAILED",
    domain: "MARKETPLACE",
    severity: "WARNING",
    emailEligible: true,
    description: "TikTok synchronization failed.",
  },
];

export function getRknBusinessEvent(key: string) {
  return RKN_BUSINESS_EVENT_CATALOG.find((event) => event.key === key) ?? null;
}