/* RKN_GLOBAL_BUSINESS_ENGINE_V1 */

import type { RknBusinessDomainDefinition } from "./contracts";

export const RKN_BUSINESS_DOMAIN_REGISTRY: readonly RknBusinessDomainDefinition[] = [
  {
    key: "ORDER",
    // RKN_ORDER_LIVE_GATE_V1
    label: "Order",
    mode: "LIVE",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: true,
    writesAllowed: true,
    existingSurfaces: [
      "business_event",
      "business_order",
      "business_order_line",
      "order_allocation",
      "ingestCanonicalOrderObservationV11",
      "globalBusinessCore",
    ],
    responsibilities: [
      "normalize order observation",
      "resolve store and SKU identity",
      "route ambiguity to review",
      "produce idempotent order events",
    ],
  },
  {
    key: "INVENTORY",
    label: "Inventory",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "inventory_balance",
      "inventory_ledger",
      "order_allocation",
      "applyInventoryAdjustment",
      "inventoryCore",
    ],
    responsibilities: [
      "allocation",
      "stock ledger",
      "balance read model",
      "reversal and reconciliation",
    ],
  },
  {
    key: "COSTING_HPP",
    label: "HPP & Costing",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "hpp_master",
      "hpp_history",
      "lookupHistoricalHpp",
      "upsertHppRecord",
    ],
    responsibilities: [
      "effective-date HPP",
      "cost snapshot",
      "COGS input",
      "costing reconciliation",
    ],
  },
  {
    key: "BORROW_TRANSFER",
    label: "Borrow & Transfer",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "existing borrow/transfer domain signals from G3A",
      "inventory ledger boundary",
      "transaction ledger boundary",
    ],
    responsibilities: [
      "borrow out",
      "borrow in",
      "inter-seller transfer",
      "stock debt and settlement",
    ],
  },
  {
    key: "PAYROLL",
    label: "Payroll",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "payroll_department",
      "worker",
      "worker_department_assignment",
      "existing payroll signals from G3A",
    ],
    responsibilities: [
      "piece-rate resolution",
      "effective rate snapshot",
      "controlled override",
      "payroll posting",
    ],
  },
  {
    key: "FINANCE_SETTLEMENT",
    label: "Finance & Settlement",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "transaction_ledger",
      "hpp history",
      "existing finance/settlement signals from G3A",
    ],
    responsibilities: [
      "sales ledger",
      "fees",
      "refunds",
      "marketplace settlement",
      "profit read model",
    ],
  },
  {
    key: "AUTOMATION",
    label: "Automation",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "automation_engine_config",
      "automation_job",
      "automation_run",
      "automation_idempotency_receipt",
    ],
    responsibilities: [
      "schedule safe work",
      "retry",
      "deduplicate",
      "route failures to review",
    ],
  },
  {
    key: "REVIEW_RECON",
    label: "Review & Reconciliation",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "automation_review_queue",
      "reconciliation_state",
    ],
    responsibilities: [
      "quarantine ambiguity",
      "surface mismatch",
      "reconcile read models",
      "manual approval boundary",
    ],
  },
  {
    key: "EMAIL_NOTIFICATION",
    label: "Email & Notification",
    mode: "SHADOW",
    readiness: "FOUNDATION_ONLY",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "auth email fields",
      "notification signals",
      "whatsapp_message_outbox pattern",
      "integration EMAIL connector",
    ],
    responsibilities: [
      "provider-neutral email contract",
      "template registry",
      "outbox boundary",
      "delivery and retry boundary",
    ],
  },
  {
    key: "IDEMPOTENCY",
    label: "Idempotency",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "automation_idempotency_receipt",
      "business_event",
      "source event identity",
    ],
    responsibilities: [
      "apply once",
      "duplicate suppression",
      "source event receipt",
    ],
  },
  {
    key: "MARKETPLACE",
    label: "Marketplace",
    mode: "SHADOW",
    readiness: "EXTEND_EXISTING",
    liveEffectsEnabled: false,
    writesAllowed: false,
    existingSurfaces: [
      "marketplace file parser",
      "Shopee connector foundation",
      "TikTok file intelligence",
      "integration registry",
    ],
    responsibilities: [
      "ingest provider event",
      "normalize provider payload",
      "never mutate ERP business state directly",
      "connector health",
    ],
  },
];

export function getRknBusinessDomain(key: string) {
  return RKN_BUSINESS_DOMAIN_REGISTRY.find((domain) => domain.key === key) ?? null;
}